# Generated by Django 3.0.8 on 2020-07-28 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='group_name',
            field=models.CharField(default='Number 1', max_length=100),
            preserve_default=False,
        ),
    ]
